### PR TITLE
works with minimal modification and dev versions of KnetLayers, Knet, AutoGrad

### PR DESCRIPTION
**Pull request by denizyuret**
We should tag a new version of KnetLayers and test a couple of experiments to see if anything changed. We might be able to upgrade the code with minimal effort!

### CODE REVIEW

**Comment by denizyuret** [comment]
Also works with released AutoGrad, Knet and KnetLayers https://github.com/ekinakyurek/KnetLayers.jl/pull/12

**Comment by ekinakyurek** [comment]
should we merge current PRs?

**Comment by denizyuret** [comment]
Sure, and I think they still replicate paper results.

Then we gotta work on making all pretrained models easy to use and get the
poster ready.

**Comment by denizyuret** [comment]
Just added compat entries in Project.toml for the latest tagged versions of AutoGrad, Knet, KnetLayers. Please test and merge.

**Pull request merged**
